### ISSUE TITLE
Missing libraries re.h and rew.h

### ISSUE THREAD

**Issue by onovo1** [alfredh/repcpc#1]
Libraries re.h and rew.h are missing.

**Comment by alfredh** [comment]
you need to install libre and librew first:

http://www.creytiv.com/re.html
https://github.com/alfredh/rew

**Comment by onovo1** [comment]
hi.
Thanks for your answer!

I tried to install libre from your git hub too but the compiler complain about missing .h files too.

Oscar





Sent from my Samsung device


-------- Original message --------

**Comment by onovo1** [comment]
I have downloaded your Librew implementation since I understand that both repcpc and repcpd implementations depend on it but Librew does not compile either. It complains about missing libraries too:

src/shim/shim.c:2:22: fatal error: re_types.h: No such file or directory
 #include <re_types.h>

**Comment by alfredh** [comment]
You need to install libre first (http://www.creytiv.com/re.html)

**Comment by onovo1** [comment]
Hi,

Thanks. I managed to install the client and the daemon of repcp. However, I cannot add any rule into the system. This is my  repcpd.conf file:

```
daemon			yes
debug			no
udp_listen		10.0.0.210:5351

external_interface	wlan0
module			iptables.so
module			announce.so
module			map.so
module			peer.so
module			syslog.so

proxy_target		10.0.0.210:5351
```
And I send the following rule to the daemon:

```
 ./repcpc -s 10.0.0.210:5351 -i 3000 -l 3600 -e 232.168.0.5:3000 -v MAP
rand: rand_u32: random not inited
rand: rand_u32: random not inited
PCP request `MAP' to PCP-Server at 10.0.0.210:5351
lifetime = 3600 sec, protocol = UDP, internal_port = 3000, external = 232.168.0.5:3000

PCP Response: Response MAP 3600sec result=SUCCESS, epoch_time=1881 sec
 nonce    = abbacd29ec4aff517369c667
 protocol = UDP
 int_port = 3000
 ext_addr = 10.0.0.210:3000
```

The answer of the daemon is the following:
```
pcp: received 60 bytes from 10.0.0.210:39339
pcp: Request MAP 3600sec client_addr=10.0.0.210
iptables: command [iptables -t nat -A REPCPD-MAP -p UDP --dport 3000 -j DNAT --to 10.0.0.210:3000]
map: created mapping: proto=UDP int=10.0.0.210:3000 <---> ext=10.0.0.210:3000 (3600sec)
pcp: received 60 bytes from 10.0.0.210:39339
pcp: Request MAP 0sec client_addr=10.0.0.210
iptables: command [iptables -t nat -D REPCPD-MAP -p UDP --dport 3000 -j DNAT --to 10.0.0.210:3000]
mapping: deleted: proto=UDP int=10.0.0.210:3000 <----> ext=10.0.0.210:3000
```
For some reason, the daemon keeps on removing the mapping. Any idea what I am doing wrong?

**Comment by onovo1** [comment]
In addition, it seems the third party address and lifetime options are not taken by the server either.

**Comment by alfredh** [comment]
can you try to add the -w option to repcpc ?

(The Mapping will be deleted when repcpc quits)

**Comment by onovo1** [comment]
Yes, adding the -w option creates the mapping until the repcpc quits. However, I am wondering if that is the behaviour defined in the RFC. If I understand correctly the draft, the rules should be deleted if the lifetime if 0. Otherwise, it should stay until the lifetime expires. 

I think the third-party option is not working either.

**Comment by onovo1** [comment]
Hi,
I have add couple of pull requests in your rew and repcpd libraries to fix both issues. Now, it should be fixed with my patches. 
You can check the code and let me know.
